[test]
# coverage is controlled via CLI flag (--coverage)
root = "packages"
coverageDir = ".coverage"
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "node_modules/**",
  "**/test/**",
  "**/dist/**",
  "**/.cache/**",
  "**/fixtures/**"
]
